# Generated by Django 5.1.3 on 2024-11-23 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.CharField(max_length=70)),
                ('arrival', models.CharField(max_length=70)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seats', models.PositiveIntegerField(default=30)),
                ('duration', models.DurationField()),
                ('transportation_choice', models.CharField(choices=[('Bus', 'Bus')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('selected_time', models.TimeField()),
                ('journey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.journey')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_ticket', models.PositiveIntegerField(default=1)),
                ('child_ticket', models.PositiveIntegerField(default=0)),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.journey')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.times')),
            ],
        ),
    ]
